version: "3.8"

services:
  backend:
    build: .
    container_name: task-manager-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:15
    container_name: task-manager-db
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: task-manager-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
    driver: local
