from django.urls import path
from .views import (
    check_auth_user,
    TokenRefresh,
    sign_in,
    sign_out,
    create_user,
    get_users,
    edit_user,
    delete_user,
    create_task,
    get_notifications,
    get_tasks,
    get_user_tasks,
    edit_task,
    delete_task,
    CountView,
    UserTaskCountView,
    StatusCountView,
    UpcomingDeadlinesView,
    ForgotPasswordView,
    ResetPasswordView,
)

urlpatterns = [
    path("check-auth-user/", check_auth_user, name="check_auth_user"),
    path("token/refresh/", TokenRefresh.as_view(), name="token_refresh"),
    path("sign-in/", sign_in, name="sign-in"),
    path("sign-out/", sign_out, name="sign_out"),
    path("add-user/", create_user, name="create-user"),
    path("get-users/", get_users, name="get-users"),
    path("edit-user/<int:user_id>/", edit_user, name="edit-user"),
    path("delete-user/<int:user_id>/", delete_user, name="delete-user"),
    path("add-task/", create_task, name="create-task"),
    path("get-tasks/", get_tasks, name="get-tasks"),
    path("get-user-tasks/<int:user_id>/",
         get_user_tasks, name="get-user-tasks"),
    path("edit-task/<int:task_id>/", edit_task, name="edit-task"),
    path("delete-task/<int:task_id>/", delete_task, name="delete-task"),
    path("get-counts/", CountView.as_view(), name="get_counts"),
    path("get-user-tasks-counts/<int:user_id>/",
         UserTaskCountView.as_view(), name="get_user_task_counts"),
    path("get-status-counts/", StatusCountView.as_view(), name="get_status_counts"),
    path("get-upcoming-deadlines/", UpcomingDeadlinesView.as_view(),
         name="get-upcoming-deadlines"),
    path("get-notifications/<int:user_id>/",
         get_notifications, name="get-notifications"),
    path('forgot-password/', ForgotPasswordView.as_view(), name='forgot-password'),
    path('reset-password/<str:token>/',
         ResetPasswordView.as_view(), name='reset-password'),
]
