# Generated by Django 5.1.7 on 2025-04-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(default='medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
